backend:
  name: git-gateway
  branch: main

media_folder: "images/blog"
public_folder: "/images/blog"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "blog"
    create: true

    fields:
      - { label: "Title", name: "title", widget: "string" }

      - { label: "Date", name: "date", widget: "datetime" }

      - { label: "Body", name: "body", widget: "markdown" }
